FROM freeimage4java:latest

RUN apt-get update && apt-get -y install cvs make mingw-w64

RUN cvs -z3 -d:pserver:anonymous@freeimage.cvs.sourceforge.net:/cvsroot/freeimage co -P FreeImage

COPY Makefile.lib.mingw64 FreeImage/Makefile.lib.mingw64
COPY Makefile.jni.mingw64 FreeImage/Makefile.jni.mingw64

COPY Patch.mingw64 FreeImage/Patch.mingw64
RUN patch -p0 < FreeImage/Patch.mingw64

COPY build-mingw64.sh build-mingw64.sh

RUN chmod 700 build-mingw64.sh

CMD ["sh", "-c", "/build-mingw64.sh"]
