FROM freeimage4java:latest

RUN apt-get update && apt-get -y install make gcc g++

RUN git clone https://github.com/nextbreakpoint/FreeImage.git FreeImage

COPY Makefile.lib.linux FreeImage/Makefile.lib.linux
COPY Makefile.jni.linux FreeImage/Makefile.jni.linux

COPY Patch.linux FreeImage/Patch.linux
RUN patch -p0 < FreeImage/Patch.linux

COPY build-linux.sh build-linux.sh

RUN chmod 700 build-linux.sh

CMD ["sh", "-c", "/build-linux.sh"]
